### implement all 4 regression  
### notebook --> what is linear regression , ridge , lasso , elastic net (in breif)

In [ ]:
import pandas as pd

from sklearn.model_selection import train_test_split

from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Ridge, Lasso, ElasticNet

from sklearn.metrics import r2_score

In [ ]:
df = pd.read_csv("https://github.com/Lakshay-Gautam-767/Datasets/raw/main/insurance.csv")

In [ ]:
df.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [ ]:
X = df.drop(columns = ["charges"])

y = df["charges"]

In [ ]:
df['region'].value_counts()

region
southeast    364
southwest    325
northwest    325
northeast    324
Name: count, dtype: int64

In [ ]:
X['sex'] = df['sex'].map({"male":1, "female":0})
X['smoker'] = df['smoker'].map({"yes":1, "no":0})
X['region'] = df['region'].map({"southeast":0, "southwest":1, "northwest":2, "northeast":3})

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [ ]:
# Linear Regression
lr = LinearRegression()

lr.fit(X_train, y_train)

y_pred = lr.predict(X_test)

print(r2_score(y_test, y_pred))

0.7839279776463969

In [ ]:
# Ridge Regression
ridge = Ridge(alpha=1.0)

ridge.fit(X_train, y_train)

y_pred = ridge.predict(X_test)

print(r2_score(y_test, y_pred))

0.783643693427773

In [ ]:
# Lasso Regression
lasso = Lasso(alpha=0.1)

lasso.fit(X_train, y_train)

y_pred = lasso.predict(X_test)

print(r2_score(y_test, y_pred))

0.783924901984132

In [ ]:
# Elastic Net
elastic = ElasticNet(alpha=0.1, l1_ratio=0.5)

elastic.fit(X_train, y_train)

y_pred = elastic.predict(X_test)

print(r2_score(y_test, y_pred))

0.7408243247692053